name: notes_mspacman-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pandas
  - numpy
  - scipy
  - pyfftw
  - pip:
    - matplotlib
    - scikit-learn
    - mne
    - h5py
    - "ipython[all]"
    - "git+https://github.com/davidlu89/pytf.git"
    - "git+https://github.com/davidlu89/mspacman.git"
    - pacpy
    - "git+https://github.com/pactools/pactools.git"
